# ARCHIVO PARA PROVISIONAMIENTO DEL BALANCEADOR DE CARGA
#
#
- hosts: loadBalancer
  sudo: yes
  gather_facts: no
  tasks:
  - name: install haproxy
    yum:
     name: haproxy
           
  - name: write our haproxy.cfg 
    template: 
      src: /etc/haproxy/haproxy.cfg 
      dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

  - name: start haproxy
    service: 
      name: haproxy 
      state: started
  - name: restart haproxy
    service:
     name: haproxy
     state: restarted



